#!/usr/bin/env bash

# Copyright 2024 Raffaele Mancuso
# SPDX-License-Identifier: MIT

# Requires wf-recorder: https://github.com/ammen99/wf-recorder

SIGNAL=1
pidf="/tmp/waybar-screenrecorder"

# Detectamos automáticamente la salida de audio actual y le agregamos ".monitor"
AUDIO_DEVICE="$(pactl get-default-sink).monitor"

# Le pasamos el dispositivo específico a --audio
WF_RECORDER_OPTS="--audio=$AUDIO_DEVICE --codec libx264rgb --codec-audio aac --params crf=18"

VIDEOEXT="mp4"

if [ "$1" == "status" ]; then
    if [ -s "$pidf" ]; then
        # Agregamos \"class\":\"recording\" al JSON
        awk 'BEGIN{printf "{\"text\":\"\", \"class\":\"recording\", \"tooltip\":\"Recording\\n"}
        NR==1{printf "PID: %s\\n", $0}
        NR==2{printf "Save to: %s\\n", $0}
        NR==3{printf "Log to: %s\"}\n", $0}' "$pidf"
    else
        # Agregamos \"class\":\"stopped\" al JSON por si quieres darle otro color después
        printf '{"text":"", "tooltip":"Stopped", "class":"stopped"}\n'
    fi

elif [ "$1" == "toggle" ]; then
    if [ -s "$pidf" ]; then
        pid=$(awk 'NR==1' "$pidf")
        logf=$(awk 'NR==3' "$pidf")

        # Verificamos si el proceso sigue vivo usando "kill -0" (esto no lo mata, solo revisa)
        if kill -0 "$pid" 2>/dev/null; then
            # El proceso sigue vivo, significa que no hubo error y lo estamos deteniendo manualmente.
            kill "$pid"
            # Como fue un cierre limpio, eliminamos el archivo de log para no ensuciar la carpeta.
            rm -f "$logf"
        fi
        # Si el proceso ya había muerto (error), no entra al 'if' anterior y el log se conserva para que puedas leerlo.

        printf "" > "$pidf"
    else
        mkdir -p "$HOME/Videos/Recordings"
        bf="$HOME/Videos/Recordings/$(date +'%Y%m%dT%H%M%S')"
        vidf="$bf.$VIDEOEXT"
        logf="$bf.log"

        if [ "$2" == "fullscreen" ]; then
            wf-recorder $WF_RECORDER_OPTS --file "$vidf" 1>"$logf" 2>&1 &
        elif [ "$2" == "region" ]; then
            sleep 1
            wf-recorder $WF_RECORDER_OPTS --geometry "$(slurp)" --file "$vidf" 1>"$logf" 2>&1 &
        else
            printf "Argument \$2='%s' not valid (fullscreen/region)" "$2"
            exit
        fi

        pid=$(jobs -p | tail -n 1)
        printf "%d\n%s\n%s" "$pid" "$vidf" "$logf" > "$pidf"
        disown "$pid"
    fi
    pkill -RTMIN+$SIGNAL waybar

else
    printf "ERROR: Argument %s not valid\n" "$1"
fi
