###################
### MY PROGRAMS ###
###################

# See https://wiki.hyprland.org/Configuring/Keywords/

$terminal = kitty
$fileManager = nautilus
$menu = rofi -show drun
$scriptsPath = $HOME/.config/hypr/userScrips

#################
### AUTOSTART ###
#################

exec-once = systemctl --user start hyprpolkitagent
exec-once = swww init
exec-once = waypaper --restore
exec-once = clipse -listen 
exec-once = waybar
exec-once = wl-clip-persist --clipboard regular
exec-once = wl-clipboard copy
exec-once = dunst &
exec-once = hyprctl setcursor material_light_cursors 6
#exec-once = bongocat -c .dotfiles/configs/bongocat/bongocat.conf

#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hyprland.org/Configuring/Environment-variables/
env = XCURSOR_THEME,material_light_cursors
env = XCURSOR_SIZE,6

env = HYPRCURSOR_THEME,material_light_cursors
env = HYPRCURSOR_SIZE,6

### MONITORS ###
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/workspaces.conf

### LOOK AND FEEL ###
source = ./userConf/lookAndFeel.conf

### KEYBINDINGS ###
source = ./userConf/keybindings.conf

### WINDOWS AND WORKSPACES ###
source = ./userConf/windowsAndWorkspaces.conf

#############
### INPUT ###
#############

# https://wiki.hyprland.org/Configuring/Variables/#input
input {
    kb_layout = us, latam
    kb_options = grp:win_space_toggle
    kb_variant =
    kb_model =
    kb_rules =

    follow_mouse = 1

    sensitivity = -0.1 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = true
    }
} 

# https://wiki.hyprland.org/Configuring/Variables/#gestures
gestures {
    gesture = 3, vertical, workspace
    gesture = 3, swipe, mod:SUPER,resize
}

# Example per-device config
# See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}


###################
### PERMISSIONS ###
###################

# See https://wiki.hyprland.org/Configuring/Permissions/
# Please note permission changes here require a Hyprland restart and are not applied on-the-fly
# for security reasons

# ecosystem {
#   enforce_permissions = 1
# }

# permission = /usr/(bin|local/bin)/grim, screencopy, allow
# permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
# permission = /usr/(bin|local/bin)/hyprpm, plugin, allow
