-- Generated by HyprMon. Manual changes may be overwritten.

hl.monitor({ output = "eDP-1", mode = "1366x768@60.00", position = "0x0", scale = 1.00 })
hl.monitor({ output = "HDMI-A-1", mode = "3840x2160@30.00", position = "1366x0", scale = 1.00, mirror = "eDP-1" })
