general {
    # Comando principal para bloquear la pantalla. "pidof" evita que se abran múltiples instancias.
    lock_cmd = hyprlock
    
    # Se ejecuta justo antes de que el sistema entre en suspensión.
    # loginctl lock-session llamará automáticamente a 'lock_cmd'.
    before_sleep_cmd = loginctl lock-session
    
    # Se ejecuta al despertar de la suspensión. Enciende las pantallas rápidamente.
    after_sleep_cmd = hyprctl dispatch dpms on
}

# (Opcional) Regla para que se suspenda/bloquee por inactividad
# listener {
#     timeout = 300                                 # 5 minutos
#     on-timeout = loginctl lock-session            # Bloquea la pantalla
# }

# listener {
#     timeout = 600                                 # 10 minutos
#     on-timeout = systemctl suspend                # Suspende la PC
# }
