# Refer to https://wiki.hyprland.org/Configuring/Variables/

# Import colors for Hellwal
source = ~/.cache/hellwal/hyprland-colors.conf

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    gaps_in = 5 #5
    gaps_out = 10, 10, 10, 46 #5

    border_size = 0#2

    # https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors

    col.active_border   = $color1
    col.inactive_border = rgba(0,0,0,0)
      

    # Set to true enable resizing windows by clicking and dragging on borders and gaps
    resize_on_border = false

    # Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
    allow_tearing = false

    layout = dwindle
}


# https://wiki.hyprland.org/Configuring/Variables/#decoration

decoration {
    rounding = 5
    active_opacity = 1.0
    inactive_opacity = 1
    fullscreen_opacity = 1.0

    dim_inactive = true
    dim_strength = 0.1
    dim_special = 0.1

    shadow {
        enabled = no
        range = 5
        render_power = 20
        color = $color9
    }

    # https://wiki.hyprland.org/Configuring/Variables/#blur
    blur {
        enabled = true	
        size = 6
        passes = 2
        ignore_opacity = true
        new_optimizations = true
        special = true
        popups = true
    }
}

#https://wiki.hyprland.org/Configuring/Variables/#animations
animations {
    enabled = yes, please :)

    # Default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more

    bezier = default, 0.05, 0.9, 0.1, 1.05
    bezier = wind, 0.05, 0.9, 0.1, 1.05
    bezier = overshot, 0.13, 0.99, 0.29, 1.08
    bezier = liner, 1, 1, 1, 1
    bezier = bounce, 0.4, 0.9, 0.6, 1.0
    bezier = snappyReturn, 0.4, 0.9, 0.6, 1.0

    bezier = slideInFromRight, 0.5, 0.0, 0.5, 1.0
    animation = windows, 1, 4,  snappyReturn, slidevert
    animation = windowsIn, 1, 4, snappyReturn, slidevert right 
  
    animation = windowsOut, 1, 4, snappyReturn, slide 
    animation = windowsMove, 1, 4, bounce, slide
    #animation = layersOut, 1, 4, bounce, slidevert right
    animation = fadeIn, 1, 10, default
    animation = fadeOut, 1, 10, default
    animation = fadeSwitch, 1, 10, default
    animation = fadeShadow, 1, 10, default
    animation = fadeDim, 1, 10, default
    animation = fadeLayers, 1, 10, default
    animation = workspaces, 1, 5, overshot, slidevert #slide
    animation = border, 1, 1, liner
    animation = layers, 1, 2, bounce, default#slidevert right
    animation = borderangle, 1, 30, liner, loop
}

# layerrule = animation slidevert right, ^(rofi)$


# Ref https://wiki.hyprland.org/Configuring/Workspace-Rules/
# "Smart gaps" / "No gaps when only"
# uncomment all if you wish to use that.
# workspace = w[tv1], gapsout:0, gapsin:0
# workspace = f[1], gapsout:0, gapsin:0
# windowrule = bordersize 0, floating:0, onworkspace:w[tv1]
# windowrule = rounding 0, floating:0, onworkspace:w[tv1]
# windowrule = bordersize 0, floating:0, onworkspace:f[1]
# windowrule = rounding 0, floating:0, onworkspace:f[1]

# See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
}

# See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
master {
    new_status = master
}

# https://wiki.hyprland.org/Configuring/Variables/#misc
misc {
    force_default_wallpaper = -1 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = false # If true disables the random hyprland logo / anime girl background. :(
}
