
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Opacity
windowrule {
    name = firefox
    match:class = ^(firefox)$
    opacity = 0.95 0.9
}

windowrule {
    name = airctl
    match:class = ^(io.github.airctl)$
    float = on
    size = 300 450
}

windowrule {
    name = vscode
    match:class = ^(Code)$
    opacity = 1 0.9
}

windowrule {
    name = vscodium
    match:class = ^(VSCodium)$
    opacity = 1 0.85
}

windowrule {
    name = kitty-term
    match:class = ^(kitty)$
    opacity = 0.9 0.8
    size = 800 500
    center = on
}

windowrule {
    name = nautilus-main
    match:class = ^(org.gnome.Nautilus)$
    opacity = 0.85 0.8
    float = on
    size = 700 450
    center = on
}

windowrule {
    name = spotify
    match:class = ^(Spotify)$
    opacity = 1 0.9
}

windowrule {
    name = discord-app
    match:class = ^(discord)$
    opacity = 0.85 0.85
}

windowrule {
    name = launcher
    match:class = ^(Rofi)$
    opacity = 0.4 0.4
}

windowrule {
    name = obsidian-notes
    match:class = ^(obsidian)$
    opacity = 0.85 0.85
}

windowrule {
    name = idea-ce
    match:class = ^(jetbrains-idea-ce)$
    opacity = 1 0.85
}

windowrule {
    name = sherlock-app
    match:class = ^(sherlock)$
    opacity = 0.1 0.2
}

# Common Modals

# Nautilus
windowrule {
    name=nautilus
    match:class=^(org.gnome.Nautilus)$
    float=on
    size=(700) (450)
    center=on
} 

# Pavucontrol
windowrule {
    name=pavucontrol
    match:class=^(org.pulseaudio.pavucontrol)$
    float=on
    size=(650) (450)
    center=on
}

# Blueman Manager
windowrule {
    name=blueman
    match:class=^(blueman-manager)$
    float=on
    center=on
}

# Waypaper
windowrule {
    name=waypaper
    match:class=^(waypaper)$
    float=on
    center=on
}

# OneDriveGUI
windowrule {
    name=onedrive
    match:class=^(OneDriveGUI)$
    float=on
    size=(200) (500)
    center=on
}

# Clipse
windowrule {
    name=clipse
    match:class=(clipse)
    float=on
    size=(650) (450)
    center=on
}

# Evince (Visor de documentos)
windowrule {
    name=evince
    match:class=(org.gnome.Evince)
    float=on
    center=on
}

# IMV (Visor de imágenes)
windowrule {
    name=imv
    match:class=^(imv)$
    float=on
    center=on
}

# Network Manager
windowrule {
    name=network-manager
    match:class=^(com.network.manager)$
    float=on
    center=on
}

# Kitty (Solo tamaño, ya que float estaba comentado o implícito)
windowrule {
    name=kitty-size
    match:class=^(kitty)$
    size=(800) (500)
    center=on
}

# NWG Displays
windowrule {
    name=nwg-displays
    match:class=^(nwg-displays)$
    float=on
    size=(900) (500)
    center=onz
}