
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Opacity
windowrulev2 = opacity 0.95 0.9,class:^(firefox)$
windowrulev2 = opacity 1 0.9,class:^(Code)$
windowrulev2 = opacity 1 0.85,class:^(VSCodium)$
windowrulev2 = opacity 0.9 0.8,class:^(kitty)$
windowrulev2 = opacity 0.85 0.8,class:^(org.gnome.Nautilus)$
windowrulev2 = opacity 1 0.9,class:^(Spotify)$
windowrulev2 = opacity 0.85 0.85,class:^(discord)$
windowrulev2 = opacity 0.4 0.4,class:^(Rofi)$
windowrulev2 = opacity 0.85 0.85,class:^(obsidian)$
windowrulev2 = opacity 1 0.85,class:^(jetbrains-idea-ce)$
windowrulev2 = opacity 0.1 0.2,class:^(sherlock)$

# Common Modals

# Nautilus (Ejemplo original)
windowrule {
    name=nautilus
    match:class=^(org.gnome.Nautilus)$
    float=on
    size=(700) (450)
    center=on
} 

# Pavucontrol
windowrule {
    name=pavucontrol
    match:class=^(org.pulseaudio.pavucontrol)$
    float=on
    size=(650) (450)
    center=on
}

# Blueman Manager
windowrule {
    name=blueman
    match:class=^(blueman-manager)$
    float=on
    center=on
}

# Waypaper
windowrule {
    name=waypaper
    match:class=^(waypaper)$
    float=on
    center=on
}

# OneDriveGUI
windowrule {
    name=onedrive
    match:class=^(OneDriveGUI)$
    float=on
    size=(200) (500)
    center=on
}

# Clipse
windowrule {
    name=clipse
    match:class=(clipse)
    float=on
    size=(650) (450)
    center=on
}

# Evince (Visor de documentos)
windowrule {
    name=evince
    match:class=(org.gnome.Evince)
    float=on
    center=on
}

# IMV (Visor de imágenes)
windowrule {
    name=imv
    match:class=^(imv)$
    float=on
    center=on
}

# Network Manager
windowrule {
    name=network-manager
    match:class=^(com.network.manager)$
    float=on
    center=on
}

# Kitty (Solo tamaño, ya que float estaba comentado o implícito)
windowrule {
    name=kitty-size
    match:class=^(kitty)$
    size=(800) (500)
    center=on
}

# NWG Displays
windowrule {
    name=nwg-displays
    match:class=^(nwg-displays)$
    float=on
    size=(900) (500)
    center=onz
}